# Generated by Django 3.0.6 on 2020-05-15 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name_plural': 'Movies'},
        ),
    ]
