# Generated by Django 3.0.6 on 2020-05-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movies_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='pic',
            field=models.URLField(default='https://www.prokerala.com/movies/assets/img/no-poster-available.jpg', max_length=500),
        ),
    ]
