# Generated by Django 3.0.6 on 2020-05-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200515_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
