# Generated by Django 3.0.6 on 2020-05-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200515_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={},
        ),
        migrations.RemoveField(
            model_name='movies',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='movies',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
