# Generated by Django 3.0.6 on 2020-05-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20200515_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='pic',
            field=models.URLField(default='https://www.prokerala.com/movies/assets/img/no-poster-available.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
